(find-file (gethash "managepy" bivHash)))
(find-file (home "/.elisp/biv.el"))
(find-file (home "/.elisp/zzz.el"))
(find-file (home "/.elisp/keys.el"))
(find-file (home "/.emacs.d-preprelude/lisp/sa-code-navigation.el"))
(find-file (home "/.elisp/wishlist.el"))
(find-file (gethash "firstfile" bivHash))
